#!/bin/bash

set -x

export CURRENT_DIR=$PWD
export DEVELOPER_DIR=/Applications/Xcode14_2.app/Contents/Developer
INSTALL_DIR=#_INSTALL_DIR_#

update() {
    cd $INSTALL_DIR
    git pull
    swift package update
    sh install.sh
}

proj() {
    cd $CURRENT_DIR
    swift package generate-xcodeproj
    cd $INSTALL_DIR
    export INSTALL_DIR=$INSTALL_DIR
    ./.build/release/ik2proj
}

gen() {
    cd $CURRENT_DIR
    xcodebuild -project ik2gen.xcodeproj -target ik2gen -sdk macosx -arch arm64
    swift package generate-xcodeproj
    ./build/Release/ik2gen
}

case $1 in
    sh)
        bash
        ;;
    update)
        update
        ;;
    proj)
        proj
        ;;
    gen)
        gen
        ;;
    genproj)
        proj
        gen
        ;;
esac


