#!/bin/bash

set -x

export CURRENT_DIR=$PWD
INSTALL_DIR=#_INSTALL_DIR_#

update() {
    cd $INSTALL_DIR
    git pull
    swift package update
    sh install.sh
}

proj() {
    cd $INSTALL_DIR
    export INSTALL_DIR=$INSTALL_DIR
    ./.build/release/ik2proj
}

gen() {
    cd $CURRENT_DIR
    xcodebuild -project ik2gen.xcodeproj -target ik2gen
    ./build/Release/ik2gen
}

case $1 in
    update)
        update
        ;;
    proj)
        proj
        ;;
    gen)
        gen
        ;;
    genproj)
        proj
        gen
        ;;
esac


